### ISSUE TITLE
Automate Workgroup Meeting -  Monday, 11th September, 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [Automate-Workgroup/Automate-Workgroup#135]
## Attendees

- [x] Andre
- [x] Stephen
- [x] Miro

## Meeting Action Notes

- Don't close the issue after meeting as the GitHub action needs an _open issue_ with the label 'meeting' in order to make the new meeting issue.
- Record Action items in the body of each issue for these auto-generated meeting issues.
- Include what the Action Item is and a link to the meeting issue from which it was raised
- Mark Action Items as complete using the check box and then delete in the next meeting 

## Review Action items from previous meeting

- [ ] Check removed "ADA Due" label from Meeting GitHub is still absent - [Meeting](https://github.com/treasuryguild/Automate-Workgroup/issues/135) - @Andre-Diamond 
- [ ] Check Meeting GitHub Action does not create "ADA Due" label - [Meeting](https://github.com/treasuryguild/Automate-Workgroup/issues/135)  - @Andre-Diamond 
- [ ] Change Meeting GitHub Action label from "F8 Automate Educate Communicate" to "Automate Workgroup" label - [Meeting](https://github.com/treasuryguild/Automate-Workgroup/issues/135)  - @Andre-Diamond 
- [ ] Create Meeting issue in SNET Archive Workgroup with this format - [Meeting](https://github.com/treasuryguild/Automate-Workgroup/issues/135) - @stephen-rowan 

## Template for Agenda & Summary

 - The first comment underneath the body should be a brief Agenda
 - The second comment should be a brief summary of the meeting content

**Comment by Andre-Diamond** [comment]
Previous in series: #134

**Comment by stephen-rowan** [comment]
## Meeting Summary

### Meeting Issue

- Create Meeting Issue actions for all Project Board meetings
- Any custom Agenda is added as a comment after the action is generated

**Comment by stephen-rowan** [comment]
## Meeting Summary

### Discussion of Meeting Issues

- Create Meeting Issue actions for all Project Board meetings
- Any custom Agenda is added as a comment after the action is generated
- Maybe an action that adds a coment
